routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user', 'HomeController@user')->name('user');
Route::get('chart', 'AdminController@chart')->name('pendapatan.perbulan');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'is_order_guest'],function(){
    Route::group([
        'prefix'=>'',
        'as'=>'order_guest.'
    ],function(){
        Route::get('order_guest',['as'=>'index', 'uses'=>'PengurusController@pengurus']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'kamar_og.'
    ],function(){
        Route::get('/kamar_og',['as'=>'index', 'uses'=>'Project\KamarController@view_og']);
        Route::get('/kamar_og/getData/{id_kamar?}',['as'=>'data', 'uses'=>'Project\KamarController@index_og']);
        Route::get('/kamar_og/edit/{id_kamar}',['as'=>'edit', 'uses'=>'Project\KamarController@edit_og']);
        Route::post('/kamar_og/addData',['as'=>'add', 'uses'=>'Project\KamarController@store_og']);
        Route::get('/kamar_og/deleteData/{id_kamar?}',['as'=>'delete', 'uses'=>'Project\KamarController@destroy_og']);
        Route::get('/kamar_og/detail/{id_kamar}',['as'=>'show', 'uses'=>'Project\KamarController@show_og']);
        Route::put('/kamar_og/updateData/{id_kamar}',['as'=>'update', 'uses'=>'Project\KamarController@update_og']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'ruangan_og.'
    ],function(){
        Route::get('ruangan_og',['as'=>'index', 'uses'=>'Project\RuanganController@view_og']);
        Route::get('ruangan_og/getData/{id_ruangan?}',['as'=>'data', 'uses'=>'Project\RuanganController@index_og']);
        Route::post('ruangan_og/addData',['as'=>'add', 'uses'=>'Project\RuanganController@store_og']);
        Route::get('ruangan_og/deleteData/{id_ruangan?}',['as'=>'delete', 'uses'=>'Project\RuanganController@destroy_og']);
        Route::put('ruangan_og/updateData/{id_ruangan}',['as'=>'update', 'uses'=>'Project\RuanganController@update_og']);
        Route::get('ruangan_og/detail/{id_ruangan}',['as'=>'show', 'uses'=>'Project\RuanganController@show_og']);
        Route::get('ruangan_og/edit/{id_ruangan}',['as'=>'edit', 'uses'=>'Project\RuanganController@edit_og']);
    });
});

Route::group(['middleware'=>'is_pengurus'],function(){
    Route::group([
        'prefix'=>'',
        'as'=>'pengurus.'
    ],function(){
        Route::get('pengurus',['as'=>'index', 'uses'=>'PengurusController@pengurus']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'layanan_fo.'
    ],function(){
        Route::get('layanan_fo',['as'=>'index', 'uses'=>'Project\LayananController@view_fo']);
        Route::get('layanan_fo/getData/{id_layanan?}',['as'=>'data', 'uses'=>'Project\LayananController@index_fo']);
        Route::post('layanan_fo/addData',['as'=>'add', 'uses'=>'Project\LayananController@store']);
        Route::get('layanan_fo/deleteData/{id_layanan?}',['as'=>'delete', 'uses'=>'Project\LayananController@destroy_fo']);
        Route::post('layanan_fo/updateData`',['as'=>'update', 'uses'=>'Project\LayananController@update_fo']);
        Route::post('layanan_fo/import_excel`',['as'=>'import', 'uses'=>'Project\LayananController@import_excel_fo']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'kategori_layanan_fo.'
    ],function(){
        Route::get('kategori_layanan_fo',['as'=>'index', 'uses'=>'Project\KategoriLayananController@view_fo']);
        Route::get('kategori_layanan_fo/getData/{id_kategori_layanan?}',['as'=>'data', 'uses'=>'Project\KategoriLayananController@index_fo']);
        Route::post('kategori_layanan_fo/addData',['as'=>'add', 'uses'=>'Project\KategoriLayananController@store_fo']);
        Route::get('kategori_layanan_fo/deleteData/{id_kategori_layanan?}',['as'=>'delete', 'uses'=>'Project\KategoriLayananController@destroy_fo']);
        Route::post('kategori_layanan_fo/updateData',['as'=>'update', 'uses'=>'Project\KategoriLayananController@update_fo']);
        Route::post('kategori_layanan_fo/import_excel',['as'=>'import', 'uses'=>'Project\KategoriLayananController@import_excel_fo']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'tamu_fo.'
    ],function(){
        Route::get('tamu_fo',['as'=>'index', 'uses'=>'Project\TamuController@view_fo']);
        Route::get('tamu_fo/getData/{id_tamu?}',['as'=>'data', 'uses'=>'Project\TamuController@index_fo']);
        Route::post('tamu_fo/addData',['as'=>'add', 'uses'=>'Project\TamuController@store_fo']);
        Route::get('tamu_fo/deleteData/{id_tamu?}',['as'=>'delete', 'uses'=>'Project\TamuController@destroy_fo']);
        Route::post('tamu_fo/updateData',['as'=>'update', 'uses'=>'Project\TamuController@update_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'fasilitas_fo.'
    ],function(){
        Route::get('fasilitas_fo',['as'=>'index', 'uses'=>'Project\FasilitasController@view_fo']);
        Route::get('fasilitas_fo/getData/{id_fasilitas?}',['as'=>'data', 'uses'=>'Project\FasilitasController@index_fo']);
        Route::post('fasilitas_fo/addData',['as'=>'add', 'uses'=>'Project\FasilitasController@store_fo']);
        Route::get('fasilitas_fo/deleteData/{id_fasilitas?}',['as'=>'delete', 'uses'=>'Project\FasilitasController@destroy_fo']);
        Route::post('fasilitas_fo/updateData',['as'=>'update', 'uses'=>'Project\FasilitasController@update_fo']);
        Route::post('fasilitas_fo/import_excel',['as' => 'import', 'uses'=>'Project\FasilitasController@import_excel_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'kategori_fo.'
    ],function(){
        Route::get('kategori_fo',['as'=>'index', 'uses'=>'Project\KategoriController@view_fo']);
        Route::get('kategori_fo/getData/{id_kategori?}',['as'=>'data', 'uses'=>'Project\KategoriController@index_fo']);
        Route::post('kategori_fo/addData',['as'=>'add', 'uses'=>'Project\KategoriController@store_fo']);
        Route::get('kategori_fo/deleteData/{id_kategori?}',['as'=>'delete', 'uses'=>'Project\KategoriController@destroy_fo']);
        Route::post('kategori_fo/updateData',['as'=>'update', 'uses'=>'Project\KategoriController@update_fo']);
        Route::post('kategori_fo/import_excel',['as' => 'import', 'uses'=>'Project\KategoriController@import_excel_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'kamar_fo.'
    ],function(){
        Route::get('/kamar_fo',['as'=>'index', 'uses'=>'Project\KamarController@view_fo']);
        Route::get('/kamar_fo/getData/{id_kamar?}',['as'=>'data', 'uses'=>'Project\KamarController@index_fo']);
        Route::get('/kamar_fo/edit/{id_kamar}',['as'=>'edit', 'uses'=>'Project\KamarController@edit_fo']);
        Route::post('/kamar_fo/addData',['as'=>'add', 'uses'=>'Project\KamarController@store_fo']);
        Route::get('/kamar_fo/deleteData/{id_kamar?}',['as'=>'delete', 'uses'=>'Project\KamarController@destroy_fo']);
        Route::get('/kamar_fo/detail/{id_kamar}',['as'=>'show', 'uses'=>'Project\KamarController@show_fo']);
        Route::put('/kamar_fo/updateData/{id_kamar}',['as'=>'update', 'uses'=>'Project\KamarController@update_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'ruangan_fo.'
    ],function(){
        Route::get('ruangan_fo',['as'=>'index', 'uses'=>'Project\RuanganController@view_fo']);
        Route::get('ruangan_fo/getData/{id_ruangan?}',['as'=>'data', 'uses'=>'Project\RuanganController@index_fo']);
        Route::post('ruangan_fo/addData',['as'=>'add', 'uses'=>'Project\RuanganController@store_fo']);
        Route::get('ruangan_fo/deleteData/{id_ruangan?}',['as'=>'delete', 'uses'=>'Project\RuanganController@destroy_fo']);
        Route::put('ruangan_fo/updateData/{id_ruangan}',['as'=>'update', 'uses'=>'Project\RuanganController@update_fo']);
        Route::get('ruangan_fo/detail/{id_ruangan}',['as'=>'show', 'uses'=>'Project\RuanganController@show_fo']);
        Route::get('ruangan_fo/edit/{id_ruangan}',['as'=>'edit', 'uses'=>'Project\RuanganController@edit_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'booking_fo.'
    ],function(){
        Route::get('booking_fo',['as'=>'index', 'uses'=>'Project\BookingController@view_fo']);
        Route::get('bookingcalender_fo',['as'=>'calender', 'uses'=>'Project\BookingController@calender_fo']);
        Route::get('booking_fo/getData/{id_booking?}',['as'=>'data', 'uses'=>'Project\BookingController@index_fo']);
        Route::get('booking_fo/getDataTamu/{id_booking?}',['as'=>'dataTamu', 'uses'=>'Project\BookingController@tamuList_fo']);
        Route::post('booking_fo/addData',['as'=>'add', 'uses'=>'Project\BookingController@store_fo']);
        Route::post('booking_fo/checkInKamar',['as'=>'kamarSave', 'uses'=>'Project\BookingController@storeKamar_fo']);
        Route::post('booking_fo/checkInRuangan',['as'=>'ruanganSave', 'uses'=>'Project\BookingController@storeRuangan_fo']);
        Route::get('booking_fo/deleteData/{id_booking?}',['as'=>'delete', 'uses'=>'Project\BookingController@destroy_fo']);
        Route::post('booking_fo/updateData',['as'=>'update', 'uses'=>'Project\BookingController@update_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'sewa_kamar_fo.'
    ],function(){
        Route::get('sewa_kamar_fo',['as'=>'index', 'uses'=>'Project\SewaKamarController@view_fo']);
        Route::get('sewa_kamar_fo/getData/{id_sewa_kamar?}',['as'=>'data', 'uses'=>'Project\SewaKamarController@index_fo']);

resources/views/modul/ruang_kamar/kamar/detail_fo.blade.php
@extends('layouts.template')

@section('title')
 Detail Kamar
@endsection

@section('content')
<div class="container-fluid header-pages ">
<div class="card shadow" >
  <div class="card-header">
    Detail Kamar
  </div>
  <div class="card-body">
	<form action="{{route("kamar_fo.add")}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-sm">
                                <div class="form-group">
                                    <label for="">Nama Kamar</label>
                                    <input type="input" id="nama_kategori" class="form-control" name="nama_kamar" v-model="nama_kamar" value="{{$data->nama_kamar}}" readonly="">
                                </div>
                            </div>
                            <div class="col-sm">
                                <div class="form-group">
                                <label for="list">Kategori</label>
                                    <select name="kategori_id" id="list" v-model="kategori_id" class="form-control" readonly>
                                        <option value="{{$data->kategori_id}}">{{$data->kategori[0]->nama_kategori}}</option> 
                                        @foreach ($kategori as $datas)
                                        <option value="{{$datas->id_kategori}}"> {{ $datas->nama_kategori }} </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm">
                                <div class="form-group">
                                    <label for="list">Fasilitas</label>
                                        <select name="fasilitas_id" id="list" v-model="fasilitas_id" class="form-control" readonly>
                                            <option value="{{$data->fasilitas_id}}">{{$data->fasilitas[0]->nama_fasilitas}}</option> 
                                            @foreach ($fasilitas as $datas)
                                            <option value="{{$datas->id_fasilitas}}"> {{ $datas->nama_fasilitas }} </option>
                                            @endforeach
                                        </select>
                                </div>
                            </div>
                        </div>
        
                        <div class="row">
                                <div class="col-sm">
                                    <div class="form-group">
                                        <label for="">Harga</label>
                                        <input type="number" class="form-control" name="harga_kamar" value="{{$data->harga_kamar}}" readonly="" required>
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <div class="form-group">
                                        <label for="">Status</label>
                                        <select name="status" id="list" readonly v-model="status" class="form-control">
                                            <option value="{{$data->status}}">{{$data->status}}</option>
                                            <option value="Clean">Clean</option>
                                            <option value="In House">In House</option>
                                            <option value="Dirty">Dirty</option>
                                        </select>
                                    </div>
                                </div>
                                
                        </div>
                            
                        <label for="">Foto</label>
                        <br>
                        <img src="{{asset('data_file/'.$data->foto)}}" alt="">
                        
                        <div class="form-group">
                          <label for="">Keterangan</label>
                          <input type="input" readonly="" class="form-control" name="keterangan" value="{{$data->keterangan}}" required>
                        </div>
                    </form>    
  </div>
</div>
</div>
@stop

resources/views/modul/ruang_kamar/kamar/detail_og.blade.php
@extends('layouts.template')

@section('title')
 Detail Kamar
@endsection

@section('content')
<div class="container-fluid header-pages ">
<div class="card shadow" >
  <div class="card-header">
    Detail Kamar
  </div>
  <div class="card-body">
	<form action="{{route("kamar_fo.add")}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-sm">
                                <div class="form-group">
                                    <label for="">Nama Kamar</label>
                                    <input type="input" id="nama_kategori" class="form-control" name="nama_kamar" v-model="nama_kamar" value="{{$data->nama_kamar}}" readonly="">
                                </div>
                            </div>
                            <div class="col-sm">
                                <div class="form-group">
                                <label for="list">Kategori</label>
                                    <select name="kategori_id" id="list" v-model="kategori_id" class="form-control" readonly>
                                        <option value="{{$data->kategori_id}}">{{$data->kategori[0]->nama_kategori}}</option> 
                                        @foreach ($kategori as $datas)
                                        <option value="{{$datas->id_kategori}}"> {{ $datas->nama_kategori }} </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm">
                                <div class="form-group">
                                    <label for="list">Fasilitas</label>
                                        <select name="fasilitas_id" id="list" v-model="fasilitas_id" class="form-control" readonly>
                                            <option value="{{$data->fasilitas_id}}">{{$data->fasilitas[0]->nama_fasilitas}}</option> 
                                            @foreach ($fasilitas as $datas)
                                            <option value="{{$datas->id_fasilitas}}"> {{ $datas->nama_fasilitas }} </option>
                                            @endforeach
                                        </select>
                                </div>
                            </div>
                        </div>
        
                        <div class="row">
                                <div class="col-sm">
                                    <div class="form-group">
                                        <label for="">Harga</label>
                                        <input type="number" class="form-control" name="harga_kamar" value="{{$data->harga_kamar}}" readonly="" required>
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <div class="form-group">
                                        <label for="">Status</label>
                                        <select name="status" id="list" readonly v-model="status" class="form-control">
                                            <option value="{{$data->status}}">{{$data->status}}</option>
                                            <option value="Clean">Clean</option>
                                            <option value="In House">In House</option>
                                            <option value="Dirty">Dirty</option>
                                        </select>
                                    </div>
                                </div>
                                
                        </div>
                            
                        <label for="">Foto</label>
                        <br>
                        <img src="{{asset('data_file/'.$data->foto)}}" alt="">
                        
                        <div class="form-group">
                          <label for="">Keterangan</label>
                          <input type="input" readonly="" class="form-control" name="keterangan" value="{{$data->keterangan}}" required>
                        </div>
                    </form>    
  </div>
</div>
</div>
@stop

resources/views/modul/ruang_kamar/kamar/edit_fo.blade.php
@extends('layouts.template')

@section('title')
 Edit Kamar
@endsection

@section('content')
<div class="container-fluid header-pages ">
<div class="card shadow" >
  <div class="card-header">
    Edit Kamar
  </div>
  <div class="card-body">
	<form action="{{route('kamar_fo.update',$data->id_kamar)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="row">
                            <div class="col-sm">
                                <div class="form-group">
                                    <label for="">Nama Kamar</label>
                                    <input type="input" id="nama_kategori" class="form-control" name="nama_kamar" v-model="nama_kamar" value="{{$data->nama_kamar}}" required>
                                </div>
                            </div>
                            <div class="col-sm">
                                <div class="form-group">
                                <label for="list">Kategori</label>
                                    <select name="kategori_id" id="list" v-model="kategori_id" class="form-control">
                                        <option value="{{$data->kategori_id}}">{{$data->kategori[0]->nama_kategori}}</option> 
                                        @foreach ($kategori as $datas)
                                        <option value="{{$datas->id_kategori}}"> {{ $datas->nama_kategori }} </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm">
                                <div class="form-group">
                                    <label for="list">Fasilitas</label>
                                        <select name="fasilitas_id" id="list" v-model="fasilitas_id" class="form-control">
                                            <option value="{{$data->fasilitas_id}}">{{$data->fasilitas[0]->nama_fasilitas}}</option> 
                                            @foreach ($fasilitas as $datas)
                                            <option value="{{$datas->id_fasilitas}}"> {{ $datas->nama_fasilitas }} </option>
                                            @endforeach
                                        </select>
                                </div>
                            </div>
                        </div>
        
                        <div class="row">
                                <div class="col-sm">
                                    <div class="form-group">
                                        <label for="">Harga</label>
                                        <input type="number" class="form-control" name="harga_kamar" value="{{$data->harga_kamar}}" required>
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <div class="form-group">
                                        <label for="">Status</label>
                                        <select name="status" id="list" v-model="status" class="form-control">
                                            <option value="{{$data->status}}">{{$data->status}}</option>
                                            <option value="Clean">Clean</option>
                                            <option value="In House">In House</option>
                                            <option value="Dirty">Dirty</option>
                                        </select>
                                    </div>
                                </div>
                                
                        </div>
                            
                        <label for="">Foto</label>
                        <div class="custom-file">
                            <input type="file" name="foto" class="custom-file-input" id="foto" v-on="foto" value="{{$data->foto}}" ref="fileInput" required="">
                            <label class="custom-file-label" for="foto">Choose file</label>
                        </div>
                        <br>
                        <img src="{{asset('data_file/'.$data->foto)}}" alt="">
                        
                        <div class="form-group">
                          <label for="">Keterangan</label>
                          <input type="input" class="form-control" name="keterangan" value="{{$data->keterangan}}" required>
                        </div>
                        <div class="row">
                            <div class="col-10"></div>
                            <div class="col-2"><button type="submit" class="btn btn-primary">Save Changes</button></div>
                        </div>
                    </form>    
  </div>
</div>
</div>
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<script>
    $('#foto').on('change',function(){
            //get the file name
            var fileName = $(this).val();
            //replace the "Choose a file" label
            var cleanFileName = fileName.replace('C:\\fakepath\\', "");
            $(this).next('.custom-file-label').html(cleanFileName);
        })
</script>
@stop

resources/views/modul/ruang_kamar/kamar/edit_og.blade.php
@extends('layouts.template')

@section('title')
 Edit Kamar
@endsection

@section('content')
<div class="container-fluid header-pages ">
<div class="card shadow" >
  <div class="card-header">
    Edit Kamar
  </div>
  <div class="card-body">
	<form action="{{route('kamar_og.update',$data->id_kamar)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="row">
                            <div class="col-sm">
                                <div class="form-group">
                                    <label for="">Nama Kamar</label>
                                    <input type="input" id="nama_kategori" class="form-control" name="nama_kamar" v-model="nama_kamar" value="{{$data->nama_kamar}}" required>
                                </div>
                            </div>
                            <div class="col-sm">
                                <div class="form-group">
                                <label for="list">Kategori</label>
                                    <select name="kategori_id" id="list" v-model="kategori_id" class="form-control">
                                        <option value="{{$data->kategori_id}}">{{$data->kategori[0]->nama_kategori}}</option> 
                                        @foreach ($kategori as $datas)
                                        <option value="{{$datas->id_kategori}}"> {{ $datas->nama_kategori }} </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm">
                                <div class="form-group">
                                    <label for="list">Fasilitas</label>
                                        <select name="fasilitas_id" id="list" v-model="fasilitas_id" class="form-control">
                                            <option value="{{$data->fasilitas_id}}">{{$data->fasilitas[0]->nama_fasilitas}}</option> 
                                            @foreach ($fasilitas as $datas)
                                            <option value="{{$datas->id_fasilitas}}"> {{ $datas->nama_fasilitas }} </option>
                                            @endforeach
                                        </select>
                                </div>
                            </div>
                        </div>
        
                        <div class="row">
                                <div class="col-sm">
                                    <div class="form-group">
                                        <label for="">Harga</label>
                                        <input type="number" class="form-control" name="harga_kamar" value="{{$data->harga_kamar}}" required>
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <div class="form-group">
                                        <label for="">Status</label>
                                        <select name="status" id="list" v-model="status" class="form-control">
                                            <option value="{{$data->status}}">{{$data->status}}</option>
                                            <option value="Clean">Clean</option>
                                            <option value="In House">In House</option>
                                            <option value="Dirty">Dirty</option>
                                        </select>
                                    </div>
                                </div>
                                
                        </div>
                        <br>
                        <img src="{{asset('data_file/'.$data->foto)}}" alt="">
                        
                        <div class="form-group">
                          <label for="">Keterangan</label>
                          <input type="input" class="form-control" name="keterangan" value="{{$data->keterangan}}" required>
                        </div>
                        <div class="row">
                            <div class="col-10"></div>
                            <div class="col-2"><button type="submit" class="btn btn-primary">Save Changes</button></div>
                        </div>
                    </form>    
  </div>
</div>
</div>
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<script>
    $('#foto').on('change',function(){
            //get the file name
            var fileName = $(this).val();
            //replace the "Choose a file" label
            var cleanFileName = fileName.replace('C:\\fakepath\\', "");
            $(this).next('.custom-file-label').html(cleanFileName);
        })
</script>
@stop