routes/web.php
        Route::post('satuan/import_excel', ['as'=>'import', 'uses'=>'Project\SatuanController@import_excel']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'booking.'
    ],function(){
        Route::get('booking',['as'=>'index', 'uses'=>'Project\BookingController@view']);
        Route::get('bookingcalender',['as'=>'calender', 'uses'=>'Project\BookingController@calender']);
        Route::get('booking/getData/{id_booking?}',['as'=>'data', 'uses'=>'Project\BookingController@index']);
        Route::get('booking/getDataTamu/{id_booking?}',['as'=>'dataTamu', 'uses'=>'Project\BookingController@tamuList']);
        Route::post('booking/addData',['as'=>'add', 'uses'=>'Project\BookingController@store']);
        Route::post('booking/checkInKamar',['as'=>'kamarSave', 'uses'=>'Project\BookingController@storeKamar']);
        Route::post('booking/checkInRuangan',['as'=>'ruanganSave', 'uses'=>'Project\BookingController@storeRuangan']);
        Route::get('booking/deleteData/{id_booking?}',['as'=>'delete', 'uses'=>'Project\BookingController@destroy']);
        Route::post('booking/updateData',['as'=>'update', 'uses'=>'Project\BookingController@update']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'kategori_layanan.'
    ],function(){
        Route::get('kategori_layanan',['as'=>'index', 'uses'=>'Project\KategoriLayananController@view']);
        Route::get('kategori_layanan/getData/{id_kategori_layanan?}',['as'=>'data', 'uses'=>'Project\KategoriLayananController@index']);
        Route::post('kategori_layanan/addData',['as'=>'add', 'uses'=>'Project\KategoriLayananController@store']);
        Route::get('kategori_layanan/deleteData/{id_kategori_layanan?}',['as'=>'delete', 'uses'=>'Project\KategoriLayananController@destroy']);
        Route::post('kategori_layanan/updateData',['as'=>'update', 'uses'=>'Project\KategoriLayananController@update']);
        Route::post('kategori_layanan/import_excel',['as'=>'import', 'uses'=>'Project\KategoriLayananController@import_excel']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'tamu.'
    ],function(){
        Route::get('tamu',['as'=>'index', 'uses'=>'Project\TamuController@view']);
        Route::get('tamu/getData/{id_tamu?}',['as'=>'data', 'uses'=>'Project\TamuController@index']);
        Route::post('tamu/addData',['as'=>'add', 'uses'=>'Project\TamuController@store']);
        Route::get('tamu/deleteData/{id_tamu?}',['as'=>'delete', 'uses'=>'Project\TamuController@destroy']);
        Route::post('tamu/updateData',['as'=>'update', 'uses'=>'Project\TamuController@update']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'layanan.'
    ],function(){
        Route::get('layanan',['as'=>'index', 'uses'=>'Project\LayananController@view']);
        Route::get('layanan/getData/{id_layanan?}',['as'=>'data', 'uses'=>'Project\LayananController@index']);
        Route::post('layanan/addData',['as'=>'add', 'uses'=>'Project\LayananController@store']);
        Route::get('layanan/deleteData/{id_layanan?}',['as'=>'delete', 'uses'=>'Project\LayananController@destroy']);
        Route::post('layanan/updateData`',['as'=>'update', 'uses'=>'Project\LayananController@update']);
        Route::post('layanan/import_excel`',['as'=>'import', 'uses'=>'Project\LayananController@import_excel']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'pembayaran.'
    ],function(){
        Route::get('pembayaran',['as'=>'index', 'uses'=>'Project\PembayaranController@view']);
        Route::get('pembayaran/getData/{id_pembayaran?}',['as'=>'data', 'uses'=>'Project\PembayaranController@index']);
        Route::get('pembayaran_list/getData/{id_pembayaran?}',['as'=>'pembayaran_list', 'uses'=>'Project\PembayaranController@pembayaranList']);
        Route::post('pembayaran/addData',['as'=>'add', 'uses'=>'Project\PembayaranController@store']);
        Route::post('pembayaran/beli',['as'=>'beli', 'uses'=>'Project\PembayaranController@storeLayanan']);
        Route::get('pembayaran/deleteData/{id_pembayaran?}',['as'=>'delete', 'uses'=>'Project\PembayaranController@destroy']);
        Route::post('pembayaran/updateData`',['as'=>'update', 'uses'=>'Project\PembayaranController@update']);
        Route::post('pembayaran/close`',['as'=>'close', 'uses'=>'Project\PembayaranController@close']);
        Route::post('pembayaran/open`',['as'=>'open', 'uses'=>'Project\PembayaranController@open']);
        Route::post('pembayaran/import_excel`',['as'=>'import', 'uses'=>'Project\PembayaranController@import_excel']);
        Route::get('pembayaran/item/{id_pembayaran?}',['as'=>'item', 'uses'=>'Project\PembayaranController@item']);
        Route::get('pembayaran/itemList/{id_pembayaran?}',['as'=>'itemList', 'uses'=>'Project\PembayaranController@itemList']);
        Route::get('/pembayaran/invoice/{id_pembayaran?}',['as'=>'preview', 'uses'=>'Project\PembayaranController@preview']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'sewa_kamar.'
    ],function(){
        Route::get('sewa_kamar',['as'=>'index', 'uses'=>'Project\SewaKamarController@view']);
        Route::get('sewa_kamar/getData/{id_sewa_kamar?}',['as'=>'data', 'uses'=>'Project\SewaKamarController@index']);
        // Route::post('sewa_kamar/addData',['as'=>'add', 'uses'=>'Project\SewaKamarController@store']);
        Route::get('sewa_kamar/deleteData/{id_sewa_kamar?}',['as'=>'delete', 'uses'=>'Project\SewaKamarController@destroy']);
        Route::post('sewa_kamar/updateData`',['as'=>'update', 'uses'=>'Project\SewaKamarController@update']);
        Route::post('sewa_kamar/import_excel`',['as'=>'import', 'uses'=>'Project\SewaKamarController@import_excel']);
        Route::get('/preview_check_in/{id_sewa_kamar?}',['as'=>'print', 'uses'=>'Project\SewaKamarController@print_preview']); 
    });

    Route::group([
        'prefix'=>'',
        'as'=>'sewa_ruangan.'
    ],function(){
        Route::get('sewa_ruangan',['as'=>'index', 'uses'=>'Project\SewaRuaganController@view']);
        Route::get('sewa_ruangan/getData/{id_sewa_ruangan?}',['as'=>'data', 'uses'=>'Project\SewaRuaganController@index']);
        // Route::post('sewa_ruangan/addData',['as'=>'add', 'uses'=>'Project\SewaKamarController@store']);
        Route::get('sewa_ruangan/deleteData/{id_sewa_ruangan?}',['as'=>'delete', 'uses'=>'Project\SewaRuaganController@destroy']);
        Route::post('sewa_ruangan/updateData`',['as'=>'update', 'uses'=>'Project\SewaRuaganController@update']);
        Route::post('sewa_ruangan/import_excel`',['as'=>'import', 'uses'=>'Project\SewaRuaganController@import_excel']);
        Route::get('/preview_check_in_ruangan/{id_sewa_ruangan?}',['as'=>'print', 'uses'=>'Project\SewaRuaganController@print_preview']); 
    });

    Route::group([
        'prefix'=>'',
        'as'=>'check_out_ruangan.'
    ],function(){
        Route::get('check_out_ruangan',['as'=>'index', 'uses'=>'Project\SewaRuaganController@view_check_out']);
        Route::get('check_out_ruangan/getData/{id_sewa_ruangan?}',['as'=>'data', 'uses'=>'Project\SewaRuaganController@index_check_out']);
        // Route::post('check_out_kamar/addData',['as'=>'add', 'uses'=>'Project\SewaKamarController@store']);
        // Route::get('check_out_kamar/deleteData/{id_sewa_kamar?}',['as'=>'delete', 'uses'=>'Project\SewaKamarController@destroy']);
        // Route::post('check_out_kamar/updateData`',['as'=>'update', 'uses'=>'Project\SewaKamarController@update']);
        // Route::post('check_out_kamar/import_excel`',['as'=>'import', 'uses'=>'Project\SewaKamarController@import_excel']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'check_out_kamar.'
    ],function(){
        Route::get('check_out_kamar',['as'=>'index', 'uses'=>'Project\SewaKamarController@view_check_out']);
        Route::get('check_out_kamar/getData/{id_sewa_kamar?}',['as'=>'data', 'uses'=>'Project\SewaKamarController@index_check_out']);
        // Route::post('check_out_kamar/addData',['as'=>'add', 'uses'=>'Project\SewaKamarController@store']);
        // Route::get('check_out_kamar/deleteData/{id_sewa_kamar?}',['as'=>'delete', 'uses'=>'Project\SewaKamarController@destroy']);
        // Route::post('check_out_kamar/updateData`',['as'=>'update', 'uses'=>'Project\SewaKamarController@update']);
        // Route::post('check_out_kamar/import_excel`',['as'=>'import', 'uses'=>'Project\SewaKamarController@import_excel']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'terima_barang.'
    ],function(){
        Route::get('terima_barang',['as'=>'index', 'uses'=>'Project\TerimaBarangController@view']);
        Route::get('terima_barang/getData/{id_terima_barang?}',['as'=>'data', 'uses'=>'Project\TerimaBarangController@index']);
        Route::post('terima_barang/addData',['as'=>'add', 'uses'=>'Project\TerimaBarangController@store']);
        Route::get('terima_barang/deleteData/{id_terima_barang?}',['as'=>'delete', 'uses'=>'Project\TerimaBarangController@destroy']);
        Route::post('terima_barang/updateData',['as'=>'update', 'uses'=>'Project\TerimaBarangController@update']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'laporan_kamar.'
    ],function(){
        Route::get('/laporan_kamar',['as'=>'view', 'uses'=>'Project\LaporanKamarController@view']);
        Route::get('/preview_laporan_kamar',['as'=>'preview', 'uses'=>'Project\LaporanKamarController@preview']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'laporan_tamu.'
    ],function(){
        Route::get('/laporan_tamu',['as'=>'view', 'uses'=>'Project\LaporanTamuController@view']);
        Route::get('/preview_laporan_tamu',['as'=>'preview', 'uses'=>'Project\LaporanTamuController@preview']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'laporan_keuangan.'
    ],function(){
        Route::get('/laporan_keuangan',['as'=>'view', 'uses'=>'Project\LaporanKeuanganController@view']);

app/Http/Controllers/Project/LaporanKamarController.php
<?php

namespace App\Http\Controllers\Project;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Kamar;
use Carbon\Carbon;

class LaporanKamarController extends Controller
{
    public function view(){
        return view('modul.laporan.laporan_kamar.index');
    }

    public function preview(Request $request){
        $input1 = request('tanggal1');
        $input2 = request('tanggal2');
        $today    = new Carbon($input2);
        $today->addDay();  //pass l for lion aphabet in format 
        $kamar = Kamar::where('id_kamar','>',0)->whereBetween('created_at',[$input1, $today])->get();
        // $kamar = Kamar::all();
        // $counts = Carbon::today();
        // $count = $counts->addDays(30);
        // $today = Carbon::now()->toDateToString();
        $count = Kamar::where('id_kamar','>',0)->whereBetween('created_at', array($input1, $today))->count();
        return view('modul.laporan.laporan_kamar.preview',compact("kamar","count","today", "input1", "input2"));
    }
}

resources/views/modul/laporan/laporan_kamar/index.blade.php
@extends('layouts.template')

@section('title')
 Laporan Kamar
@endsection

@section('content')
    
<div id="app">
<div class="container-fluid header-pages">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-auto mr-auto">Laporan Kamar</div>
                </div>
            </div>
            <div class="card-body">
                <div class="container">
                    <form action="{{route("laporan_kamar.preview")}}" target="_blank">
                    @csrf
                    <div class="row">
                      <div class="col-sm">
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Tanggal Awal</label>
                            <input type="date" class="form-control" name="tanggal1">
                        </div>
                      </div>
                      <div class="col-sm">
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Tanggal Akhir</label>
                            <input type="date" class="form-control" name="tanggal2">
                        </div>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                  </div>
            </div>
        </div>
    </div>
    
    
</div>

<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
{{-- <script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script> --}}

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />
<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js" defer></script>
<script src = "http://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js" defer ></script>
<script src = "https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js" defer ></script>
<script src = "https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js" defer ></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" defer ></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js" defer ></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js" defer ></script>
<script src = "https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js" defer ></script>
<script src = "https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js" defer ></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script type="text/javascript">
    $(document).ready(function(){
        $('#table').DataTable({
            "columnDefs": [ {
                "targets": 'no-sort',
                "orderable": false,
            } ],
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            dom: 'Blfrtip',
            buttons: ['excel'],
            "lengthChange": true,
            "oLanguage": {
                "sZeroRecords": "",
                "sEmptyTable": ""
            }
        });
    });

    // window.onload = function () {
        var app = new Vue({
            el:'#app',
            data:{
                id_pembayaran:"",
                tamu:"",
                nama_tamu:"",
                kategori_id:"",
                harga_kamar:"",
                tamu_id:"",
                status:"",
                nama_kategori:"",
                kamar:"",
                ruangan:"",
                layanan:"",
                nama_ruangan:"",
                nama_kamar:"",
                nama_layanan:"",
                kamar_id:"",
                ruangan_id:"",
                layanan_id:"",
                total_harga:"",
                cara_bayar:"",
                datas:[],
                bayar:[],

            },
            mounted(){
                this.getData();
            },

            methods:{
                getData(){
                    var self=this;
                    axios.get("{{route('pembayaran.data')}}").then(function(response){
                        self.datas = response.data;
                    });
                },

                addData(){
                    var self=this;
                    var url="{{route('kategori.add')}}";
                    
                    var formData = new FormData();
                    formData.append("nama_kategori", self.nama_kategori);
                    formData.append("status", self.status);
                    formData.append("keterangan", self.keterangan);
                    if(self.nama_kategori == null){
                        swal("Error", "Nama Kategori Tidak Boleh Kosong", "error");
                    }
                    else if(self.status == null){
                        swal("Error", "Status Tidak Boleh Kosong", "error");
                    }
                    else{
                        axios.post(url, formData).then(function(response){
                            $('#tambahKategoriModal').modal('hide');
                            self.getData();
                            self.addBtn();
                            swal("Success", "Data berhasil disimpan", "success");
                        }).catch(function(err){
                            swal("Error", "Koneksi ke Database Gagal", "error");
                        })
                    }
                },

                deleteData(id_pembayaran){
                    var self=this;
                    var url = "{{route('pembayaran.delete')}}"+"/"+id_pembayaran;

                    var konfirm = confirm("Apakah anda yakin akan mendelete data ini?");
                    if (!konfirm) {
                        return false;
                    }
                    axios.get(url).then(function(resposnse){
                        // alert(response.data.status);
                        self.getData();
                        swal("Sukses", "Data berhasil dihapus", "error");
                    }).catch(function(err){
                        swal("Error", "Koneksi ke Database Gagal", "error");
                    })
                },

                searchData(id_pembayaran){
                    var url = "{{route('pembayaran.data')}}" + "/" + id_pembayaran;
                    var self=this;
                    var konfirm = confirm("Apakah anda yakin akan mengupdate data ini?");
                    if (!konfirm) {
                        $('#editKategoriModal').modal('hide')
                        return false;
                    }else{
                        $('#editKategoriModal').modal('show')
                    }
                    axios.get(url).then(function (response){
                        self.tamu_id = response.data.tamu_id;
                        self.status = response.data.status;
                        self.id_pembayaran = response.data.id_pembayaran;
                    })
                },

                addBtn(){
                    var url = "{{route('kategori.data')}}";
                    var self=this;
                    axios.get(url).then(function (response){
                        self.nama_kategori = null;
                        self.status = null;
                        self.keterangan = null;
                        self.id_kategori = null;
                    })
                },

                updateData(){
                    var self = this;
                    var url = "{{route('pembayaran.update')}}";
                    console.log("save");

                    var formData = new FormData();
                    formData.append("tamu_id", self.tamu_id);
                    formData.append("status", self.status);
                    formData.append("id_pembayaran", self.id_pembayaran);

                    axios.post(url, formData).then(function(response){
                        // alert(response.data.status);
                        swal("Sukses", "Data berhasil diupdate", "success");
                        self.getData();
                    }).catch(function(err){
                        swal("Error", "Koneksi ke Database Gagal", "error");
                    })
                },

                bayarData(id_pembayaran){
                    var url = "{{route('pembayaran.pembayaran_list')}}" + "/" + id_pembayaran;
                    var self=this;
                    swal("Error","Masih dalam pengerjaan","error");
                    var konfirm = confirm("Apakah anda yakin akan mengupdate data ini?");
                    if (!konfirm) {
                        $('#pembayaranModal').modal('hide');
                        return false;
                    }else{
                        $('#pembayaranModal').modal('show');
                        axios.get(url).then(function (response){
                            self.bayar = response.data;
                            // 
                        });
                    }
                },

                // getTamu() {
                //     var self = this;
                //     axios.get("{{route('tamu.data')}}").then(function(response) {
                //         self.tamulist = response.data;
                //     });
                //     console.log("data berhasil diload");
                //     // this.$swal('Hello Vue world!!!');
                // },
            }
        })

    
    </script>

@endsection

resources/views/modul/laporan/laporan_kamar/preview.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Print Laporan Data Barang</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('original/css/style.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('bootstrap/css/bootstrap.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('bootstrap/css/bootstrap-grid.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('fontawesome/css/all.css')}}">
    <style type="text/css" media="screen">
        .judul .title {
            font-size: 20px;
            font-weight: bold;
        }
        
        .tables {
            padding-top: 30px;
        }
    </style>
</head>

<body>
    <div class="judul">

        <div class="title" style="text-align: center; color: black; font-size: 32px; font-style: bold;">
            SMESA EDOTEL
        </div>
        <div class="title" style="text-align: center; color: red; font-size: 24px;">
            Laporan Kamar
        </div>


        <table>
            <tr>
                <th>Periode : </th>
                <th style="font-style: italic;">{{$input1}} s/d {{$input2}}</th>
            </tr>
        </table>
        <div>Total : {{$count}} data</div>
        <!-- <div>Periode : {{$today}}</div> -->

        
    </div>
    <div class="container">
    <div class="tables" style="padding-top: 30px;">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Nama Kamar</th>
                    <th scope="col">Kategori</th>
                    <th scope="col">Fasilitas</th>
                    <th scope="col">Harga Kamar</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($kamar as $no=> $data)
                <tr>
                    <td>{{$no+1}}</td>
                    <td>{{$data->nama_kamar}}</td>
                    <td>{{$data->kategori[0]->nama_kategori}}</td>
                    <td>{{$data->fasilitas[0]->nama_fasilitas}}</td>
                    <td>{{$data->harga_kamar}}</td>
                    <td>{{$data->status}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    </div>
    <script type="text/javascript">
        window.print();
    </script>

</body>

</html>