routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user', 'HomeController@user')->name('user');
Route::get('chart', 'AdminController@chart')->name('pendapatan.perbulan');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'is_order_guest'],function(){
    Route::group([
        'prefix'=>'',
        'as'=>'order_guest.'
    ],function(){
        Route::get('order_guest',['as'=>'index', 'uses'=>'PengurusController@pengurus']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'kamar_og.'
    ],function(){
        Route::get('/kamar_og',['as'=>'index', 'uses'=>'Project\KamarController@view_og']);
        Route::get('/kamar_og/getData/{id_kamar?}',['as'=>'data', 'uses'=>'Project\KamarController@index_og']);
        Route::get('/kamar_og/edit/{id_kamar}',['as'=>'edit', 'uses'=>'Project\KamarController@edit_og']);
        Route::post('/kamar_og/addData',['as'=>'add', 'uses'=>'Project\KamarController@store_og']);
        Route::get('/kamar_og/deleteData/{id_kamar?}',['as'=>'delete', 'uses'=>'Project\KamarController@destroy_og']);
        Route::get('/kamar_og/detail/{id_kamar}',['as'=>'show', 'uses'=>'Project\KamarController@show_og']);
        Route::put('/kamar_og/updateData/{id_kamar}',['as'=>'update', 'uses'=>'Project\KamarController@update_og']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'ruangan_og.'
    ],function(){
        Route::get('ruangan_og',['as'=>'index', 'uses'=>'Project\RuanganController@view_og']);
        Route::get('ruangan_og/getData/{id_ruangan?}',['as'=>'data', 'uses'=>'Project\RuanganController@index_og']);
        Route::post('ruangan_og/addData',['as'=>'add', 'uses'=>'Project\RuanganController@store_og']);
        Route::get('ruangan_og/deleteData/{id_ruangan?}',['as'=>'delete', 'uses'=>'Project\RuanganController@destroy_og']);
        Route::put('ruangan_og/updateData/{id_ruangan}',['as'=>'update', 'uses'=>'Project\RuanganController@update_og']);
        Route::get('ruangan_og/detail/{id_ruangan}',['as'=>'show', 'uses'=>'Project\RuanganController@show_og']);
        Route::get('ruangan_og/edit/{id_ruangan}',['as'=>'edit', 'uses'=>'Project\RuanganController@edit_og']);
    });
});

Route::group(['middleware'=>'is_pengurus'],function(){
    Route::group([
        'prefix'=>'',
        'as'=>'pengurus.'
    ],function(){
        Route::get('pengurus',['as'=>'index', 'uses'=>'PengurusController@pengurus']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'layanan_fo.'
    ],function(){
        Route::get('layanan_fo',['as'=>'index', 'uses'=>'Project\LayananController@view_fo']);
        Route::get('layanan_fo/getData/{id_layanan?}',['as'=>'data', 'uses'=>'Project\LayananController@index_fo']);
        Route::post('layanan_fo/addData',['as'=>'add', 'uses'=>'Project\LayananController@store']);
        Route::get('layanan_fo/deleteData/{id_layanan?}',['as'=>'delete', 'uses'=>'Project\LayananController@destroy_fo']);
        Route::post('layanan_fo/updateData`',['as'=>'update', 'uses'=>'Project\LayananController@update_fo']);
        Route::post('layanan_fo/import_excel`',['as'=>'import', 'uses'=>'Project\LayananController@import_excel_fo']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'kategori_layanan_fo.'
    ],function(){
        Route::get('kategori_layanan_fo',['as'=>'index', 'uses'=>'Project\KategoriLayananController@view_fo']);
        Route::get('kategori_layanan_fo/getData/{id_kategori_layanan?}',['as'=>'data', 'uses'=>'Project\KategoriLayananController@index_fo']);
        Route::post('kategori_layanan_fo/addData',['as'=>'add', 'uses'=>'Project\KategoriLayananController@store_fo']);
        Route::get('kategori_layanan_fo/deleteData/{id_kategori_layanan?}',['as'=>'delete', 'uses'=>'Project\KategoriLayananController@destroy_fo']);
        Route::post('kategori_layanan_fo/updateData',['as'=>'update', 'uses'=>'Project\KategoriLayananController@update_fo']);
        Route::post('kategori_layanan_fo/import_excel',['as'=>'import', 'uses'=>'Project\KategoriLayananController@import_excel_fo']);
    });

    Route::group([
        'prefix'=>'',
        'as'=>'tamu_fo.'
    ],function(){
        Route::get('tamu_fo',['as'=>'index', 'uses'=>'Project\TamuController@view_fo']);
        Route::get('tamu_fo/getData/{id_tamu?}',['as'=>'data', 'uses'=>'Project\TamuController@index_fo']);
        Route::post('tamu_fo/addData',['as'=>'add', 'uses'=>'Project\TamuController@store_fo']);
        Route::get('tamu_fo/deleteData/{id_tamu?}',['as'=>'delete', 'uses'=>'Project\TamuController@destroy_fo']);
        Route::post('tamu_fo/updateData',['as'=>'update', 'uses'=>'Project\TamuController@update_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'fasilitas_fo.'
    ],function(){
        Route::get('fasilitas_fo',['as'=>'index', 'uses'=>'Project\FasilitasController@view_fo']);
        Route::get('fasilitas_fo/getData/{id_fasilitas?}',['as'=>'data', 'uses'=>'Project\FasilitasController@index_fo']);
        Route::post('fasilitas_fo/addData',['as'=>'add', 'uses'=>'Project\FasilitasController@store_fo']);
        Route::get('fasilitas_fo/deleteData/{id_fasilitas?}',['as'=>'delete', 'uses'=>'Project\FasilitasController@destroy_fo']);
        Route::post('fasilitas_fo/updateData',['as'=>'update', 'uses'=>'Project\FasilitasController@update_fo']);
        Route::post('fasilitas_fo/import_excel',['as' => 'import', 'uses'=>'Project\FasilitasController@import_excel_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'kategori_fo.'
    ],function(){
        Route::get('kategori_fo',['as'=>'index', 'uses'=>'Project\KategoriController@view_fo']);
        Route::get('kategori_fo/getData/{id_kategori?}',['as'=>'data', 'uses'=>'Project\KategoriController@index_fo']);
        Route::post('kategori_fo/addData',['as'=>'add', 'uses'=>'Project\KategoriController@store_fo']);
        Route::get('kategori_fo/deleteData/{id_kategori?}',['as'=>'delete', 'uses'=>'Project\KategoriController@destroy_fo']);
        Route::post('kategori_fo/updateData',['as'=>'update', 'uses'=>'Project\KategoriController@update_fo']);
        Route::post('kategori_fo/import_excel',['as' => 'import', 'uses'=>'Project\KategoriController@import_excel_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'kamar_fo.'
    ],function(){
        Route::get('/kamar_fo',['as'=>'index', 'uses'=>'Project\KamarController@view_fo']);
        Route::get('/kamar_fo/getData/{id_kamar?}',['as'=>'data', 'uses'=>'Project\KamarController@index_fo']);
        Route::get('/kamar_fo/edit/{id_kamar}',['as'=>'edit', 'uses'=>'Project\KamarController@edit_fo']);
        Route::post('/kamar_fo/addData',['as'=>'add', 'uses'=>'Project\KamarController@store_fo']);
        Route::get('/kamar_fo/deleteData/{id_kamar?}',['as'=>'delete', 'uses'=>'Project\KamarController@destroy_fo']);
        Route::get('/kamar_fo/detail/{id_kamar}',['as'=>'show', 'uses'=>'Project\KamarController@show_fo']);
        Route::put('/kamar_fo/updateData/{id_kamar}',['as'=>'update', 'uses'=>'Project\KamarController@update_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'ruangan_fo.'
    ],function(){
        Route::get('ruangan_fo',['as'=>'index', 'uses'=>'Project\RuanganController@view_fo']);
        Route::get('ruangan_fo/getData/{id_ruangan?}',['as'=>'data', 'uses'=>'Project\RuanganController@index_fo']);
        Route::post('ruangan_fo/addData',['as'=>'add', 'uses'=>'Project\RuanganController@store_fo']);
        Route::get('ruangan_fo/deleteData/{id_ruangan?}',['as'=>'delete', 'uses'=>'Project\RuanganController@destroy_fo']);
        Route::put('ruangan_fo/updateData/{id_ruangan}',['as'=>'update', 'uses'=>'Project\RuanganController@update_fo']);
        Route::get('ruangan_fo/detail/{id_ruangan}',['as'=>'show', 'uses'=>'Project\RuanganController@show_fo']);
        Route::get('ruangan_fo/edit/{id_ruangan}',['as'=>'edit', 'uses'=>'Project\RuanganController@edit_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'booking_fo.'
    ],function(){
        Route::get('booking_fo',['as'=>'index', 'uses'=>'Project\BookingController@view_fo']);
        Route::get('bookingcalender_fo',['as'=>'calender', 'uses'=>'Project\BookingController@calender_fo']);
        Route::get('booking_fo/getData/{id_booking?}',['as'=>'data', 'uses'=>'Project\BookingController@index_fo']);
        Route::get('booking_fo/getDataTamu/{id_booking?}',['as'=>'dataTamu', 'uses'=>'Project\BookingController@tamuList_fo']);
        Route::post('booking_fo/addData',['as'=>'add', 'uses'=>'Project\BookingController@store_fo']);
        Route::post('booking_fo/checkInKamar',['as'=>'kamarSave', 'uses'=>'Project\BookingController@storeKamar_fo']);
        Route::post('booking_fo/checkInRuangan',['as'=>'ruanganSave', 'uses'=>'Project\BookingController@storeRuangan_fo']);
        Route::get('booking_fo/deleteData/{id_booking?}',['as'=>'delete', 'uses'=>'Project\BookingController@destroy_fo']);
        Route::post('booking_fo/updateData',['as'=>'update', 'uses'=>'Project\BookingController@update_fo']);
    });
    Route::group([
        'prefix'=>'',
        'as'=>'sewa_kamar_fo.'
    ],function(){
        Route::get('sewa_kamar_fo',['as'=>'index', 'uses'=>'Project\SewaKamarController@view_fo']);
        Route::get('sewa_kamar_fo/getData/{id_sewa_kamar?}',['as'=>'data', 'uses'=>'Project\SewaKamarController@index_fo']);

app/Http/Controllers/Project/KategoriLayananController.php
<?php

namespace App\Http\Controllers\Project;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\KategoriLayanan;
use App\Imports\KategoriLayananImport;
use Maatwebsite\Excel\Facades\Excel;
use Session;

class KategoriLayananController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function view()
    {
        return view('modul.layanan.kategori_layanan.index');
    }
    
    public function index($id_kategori_layanan = null)
    {
        if ($id_kategori_layanan) {
            echo json_encode(KategoriLayanan::find($id_kategori_layanan));
        }else {
            echo json_encode(KategoriLayanan::all());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new KategoriLayanan;
        $data->nama_kategori_layanan = $request->nama_kategori_layanan;
        $data->status = $request->status;
        $data->keterangan = $request->keterangan;
        $data->save();

        echo json_encode(array('status'=>'Sukses Simpan'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $data = KategoriLayanan::find($request->id_kategori_layanan);
        $data->nama_kategori_layanan = $request->nama_kategori_layanan;
        $data->status = $request->status;
        $data->keterangan = $request->keterangan;
        $data->update();
        echo json_encode(array('status' => 'Sukses Update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_kategori_layanan)
    {
        $test = KategoriLayanan::find($id_kategori_layanan)->delete();
        dd($test);
        echo json_encode(array('status'=>'Sukses Menghapus'));
    }

    public function import_excel(Request $request) 
    {
        // validasi
        $this->validate($request, [
            'file' => 'required|mimes:csv,xls,xlsx'
        ]);
 
        // menangkap file excel
        $file = $request->file('file');
 
        // membuat nama file unik
        $nama_file = rand().$file->getClientOriginalName();
 
        // upload ke folder file_siswa di dalam folder public
        $file->move('file_satuan',$nama_file);
 
        // import data
        Excel::import(new KategoriLayananImport, public_path('/file_satuan/'.$nama_file));
 
        // notifikasi dengan session
        Session::flash('sukses','Data Berhasil Diimport!');
 
        // alihkan halaman kembali
        return redirect('/kategori_layanan');
    }



    //Front Office
    public function view_fo()
    {
        return view('modul.layanan.kategori_layanan.index_fo');
    }
    
    public function index_fo($id_kategori_layanan = null)
    {
        if ($id_kategori_layanan) {
            echo json_encode(KategoriLayanan::find($id_kategori_layanan));
        }else {
            echo json_encode(KategoriLayanan::all());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create_fo()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store_fo(Request $request)
    {
        $data = new KategoriLayanan;
        $data->nama_kategori_layanan = $request->nama_kategori_layanan;
        $data->status = $request->status;
        $data->keterangan = $request->keterangan;
        $data->save();

        echo json_encode(array('status'=>'Sukses Simpan'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show_fo($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit_fo($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update_fo(Request $request)
    {
        $data = KategoriLayanan::find($request->id_kategori_layanan);
        $data->nama_kategori_layanan = $request->nama_kategori_layanan;
        $data->status = $request->status;
        $data->keterangan = $request->keterangan;
        $data->update();
        echo json_encode(array('status' => 'Sukses Update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy_fo($id_kategori_layanan)
    {
        $test = KategoriLayanan::find($id_kategori_layanan)->delete();
        dd($test);
        echo json_encode(array('status'=>'Sukses Menghapus'));
    }

    public function import_excel_fo(Request $request) 
    {
        // validasi
        $this->validate($request, [
            'file' => 'required|mimes:csv,xls,xlsx'
        ]);
 
        // menangkap file excel
        $file = $request->file('file');
 
        // membuat nama file unik
        $nama_file = rand().$file->getClientOriginalName();
 
        // upload ke folder file_siswa di dalam folder public
        $file->move('file_satuan',$nama_file);
 
        // import data
        Excel::import(new KategoriLayananImport, public_path('/file_satuan/'.$nama_file));
 
        // notifikasi dengan session
        Session::flash('sukses','Data Berhasil Diimport!');
 
        // alihkan halaman kembali
        return redirect('/kategori_layanan_fo');
    }    
}

resources/views/modul/layanan/kategori_layanan/index_fo.blade.php
@extends('layouts.template')

@section('title')
 Kategori Layanan
@endsection

@section('content')
    
<div id="app">
<div class="container-fluid header-pages">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-auto mr-auto">Master Kategori Layanan</div>
                    <div class="space-button">
                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#importExcel" @click="addBtn()"><i class="fas fa-file-excel"></i> Import Excel
                        </button>
                        <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#tambahKategoriModal" @click="addBtn()">
                           <i class="fas fa-plus"></i> Tambah Kategori
                        </button>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table id="table" class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th class="no-sort" width="10">No</th>
                            <th>Nama Kategori Layanan</th>
                            <th>Status</th>
                            <th>Keterangan</th>
                            <th width="110">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(data,index) in datas">
                            <td>@{{++index}}</td>
                            <td>@{{data.nama_kategori_layanan}}</td>
                            <td>@{{data.status}}</td>
                            <td>@{{data.keterangan}}</td>
                            <td>
                                <button class="btn btn-outline-warning btn-sm" @click="searchData(data.id_kategori_layanan)" data-toggle="modal" data-target="#editKategoriModal"><i class="fas fa-edit"></i></button>
                                <button class="btn btn btn-outline-danger btn-sm" @click="deleteData(data.id_kategori_layanan)"><i class="fas fa-trash"></i></button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<div class="modal fade" id="importExcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <form method="post" action="/kategori_layanan/import_excel_fo" enctype="multipart/form-data">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Import Excel</h5>
                        </div>
                        <div class="modal-body">

                            {{ csrf_field() }}

                            <label>Pilih file excel</label>
                            <div class="form-group">
                                <input type="file" name="file" required="required">
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Import</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

<div class="modal fade bd-example-modal-lg" id="tambahKategoriModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                  <label for="">Nama Kategori Layanan</label>
                  <input type="input" id="nama_kategori_layanan" class="form-control" name="nama_kategori_layanan" v-model="nama_kategori_layanan" required>
                </div>
                <div class="form-group">
                  <label for="">Status</label>
                  <select name="status" v-model="status" required="" class="form-control">
                  <option>Aktif</option>
                  <option>Tidak Aktif</option>
                  </select>
                </div>
                <div class="form-group">
                  <label for="">Keterangan</label>
                  <input type="input" class="form-control" name="keterangan" v-model="keterangan" required>
                </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button class="btn btn-primary"  data-toggle="modal" data-target="#loadingModal" @click="addData()" data-dismiss="modal" >Submit</button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade bd-example-modal-lg" id="editKategoriModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Edit Data</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                        <div class="form-group">
                                <label for="">Nama Kategori Layanan</label>
                                <input type="input" class="form-control" name="nama_kategori_layanan" v-model="nama_kategori_layanan">
                              </div>
                              <div class="form-group">
                                <label for="">Status</label>
                                <select name="status" v-model="status" required="" class="form-control">
                                <option>Aktif</option>
                                <option>Tidak Aktif</option>
                                </select>
                                <input type="hidden" class="form-control" name="id_suplier" v-model="id_suplier">
                              </div>
                              <div class="form-group">
                                <label for="">Keterangan</label>
                                <input type="input" class="form-control" name="keterangan" v-model="keterangan">
                              </div>
                    <button class="btn btn-primary" data-dismiss="modal" @click="updateData()">Submit</button>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
</div>

<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
{{-- <script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script> --}}

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />
<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js" defer></script>
<script src = "http://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js" defer ></script>
<script src = "https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js" defer ></script>
<script src = "https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js" defer ></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" defer ></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js" defer ></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js" defer ></script>
<script src = "https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js" defer ></script>
<script src = "https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js" defer ></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script type="text/javascript">
    $(document).ready(function(){
        $('#table').DataTable({
            "columnDefs": [ {
                "targets": 'no-sort',
                "orderable": false,
            } ],
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            dom: 'Blfrtip',
            buttons: ['excel'],
            "lengthChange": true
        });
    });
    

    // window.onload = function () {
        var app = new Vue({
            el:'#app',
            data:{
                id_kategori_layanan:"",
                nama_kategori_layanan:"",
                status:"",
                keterangan:"",
                datas:[],
            },
            mounted(){
                this.getData();
            },

            methods:{
                getData(){
                    var self=this;
                    axios.get("{{route('kategori_layanan_fo.data')}}").then(function(response){
                        self.datas = response.data;
                    });
                },

                addData(){
                    var self=this;
                    var url="{{route('kategori_layanan_fo.add')}}";
                    
                    var formData = new FormData();
                    formData.append("nama_kategori_layanan", self.nama_kategori_layanan);
                    formData.append("status", self.status);
                    formData.append("keterangan", self.keterangan);
                    if(self.nama_kategori_layanan == null){
                        swal("Error", "Nama Kategori Layanan Tidak Boleh Kosong", "error");
                    }
                    else if(self.status == null){
                        swal("Error", "Status Tidak Boleh Kosong", "error");
                    }
                    else{
                        axios.post(url, formData).then(function(response){
                            self.getData();
                            swal("Success", "Data berhasil disimpan", "success");
                        }).catch(function(err){
                            swal("Error", "Koneksi ke Database Gagal", "error");
                        })
                    }
                },

                deleteData(id_kategori_layanan){
                    var self=this;
                    var url = "{{route('kategori_layanan_fo.delete')}}"+"/"+id_kategori_layanan;

                    var konfirm = confirm("Apakah anda yakin akan mendelete data ini?");
                    if (!konfirm) {
                        return false;
                    }
                    axios.get(url).then(function(resposnse){
                        // alert(response.data.status);
                        self.getData();
                        swal("Success", "Data berhasil dihapus", "success");
                    }).catch(function(err){
                        swal("Error", "Koneksi ke Database Gagal", "error");
                    })
                },

                searchData(id_kategori_layanan){
                    var url = "{{route('kategori_layanan_fo.data')}}" + "/" + id_kategori_layanan;
                    var self=this;
                    var konfirm = confirm("Apakah anda yakin akan mengupdate data ini?");
                    if (!konfirm) {
                        return false;
                    }
                    axios.get(url).then(function (response){
                        self.nama_kategori_layanan = response.data.nama_kategori_layanan;
                        self.status = response.data.status;
                        self.keterangan = response.data.keterangan;
                        self.id_kategori_layanan = response.data.id_kategori_layanan;
                    })
                    console.log(id_kategori_layanan);
                },

                addBtn(){
                    var url = "{{route('kategori_layanan_fo.data')}}";
                    var self=this;
                    axios.get(url).then(function (response){
                        self.nama_kategori_layanan = null;
                        self.status = null;
                        self.keterangan = null;
                        self.id_kategori_layanan = null;
                    })
                },

                updateData(){
                    var self = this;
                    var url = "{{route('kategori_layanan_fo.update')}}";
                    console.log("save");

                    var formData = new FormData();
                    formData.append("nama_kategori_layanan", self.nama_kategori_layanan);
                    formData.append("status", self.status);
                    formData.append("keterangan", self.keterangan);
                    formData.append("id_kategori_layanan", self.id_kategori_layanan);

                    axios.post(url, formData).then(function(response){
                        // alert(response.data.status);
                        swal("Sucess", "Data berhasil diupdate", "success");
                        self.getData();
                    }).catch(function(err){
                        swal("Error", "Koneksi ke Database Gagal", "error");
                    })
                }
            }
        })
    
    </script>
@endsection